version: '3'
services:
  web:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./www:/usr/share/nginx/html
      - ./site.conf:/etc/nginx/conf.d/site.conf
    links:
      - php
  php:
    image: php:7.2-fpm
    volumes:
      - ./www:/usr/share/nginx/html
